services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SqlPassword123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  webapi:
    build: .
    container_name: webapi
    ports:
      - "6000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=OfficeTrackDb;User Id=sa;Password=SqlPassword123;TrustServerCertificate=True;
    depends_on:
      - sqlserver

volumes:
  sql_data:
    driver: local
